const CollectionActionTypes = {
    FETCH_COLLECTIONS_START: "UPDATE_COLLECTIONS",
    FETCH_COLLECTIONS_SUCCESS: "UPDATE_COLLECTIONS",
    FETCH_COLLECTIONS_FAILURE: "UPDATE_COLLECTIONS"
}

export default CollectionActionTypes;